# Generated by Django 4.2.16 on 2024-09-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedescription',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.service'),
        ),
    ]
