# Generated by Django 4.2.16 on 2024-09-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_servicedescription_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicedescription',
            name='service',
            field=models.ForeignKey(default=1996, on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='service_app.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicedescription',
            name='title',
            field=models.CharField(max_length=125),
        ),
    ]
