# Generated by Django 4.2.16 on 2024-09-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_servicedescription_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='title_en',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='servicedescription',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
