# Generated by Django 4.2.16 on 2024-09-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyus',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_en',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_ru',
            field=models.CharField(max_length=125, null=True),
        ),
        migrations.AddField(
            model_name='whyus',
            name='title_uz',
            field=models.CharField(max_length=125, null=True),
        ),
    ]
