# Generated by Django 4.2.16 on 2024-09-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_certificate_description_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('title_en', models.CharField(max_length=125, null=True)),
                ('title_ru', models.CharField(max_length=125, null=True)),
                ('title_uz', models.CharField(max_length=125, null=True)),
                ('tic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('title_en', models.CharField(max_length=125, null=True)),
                ('title_ru', models.CharField(max_length=125, null=True)),
                ('title_uz', models.CharField(max_length=125, null=True)),
                ('price', models.IntegerField()),
                ('price_en', models.IntegerField(null=True)),
                ('price_ru', models.IntegerField(null=True)),
                ('price_uz', models.IntegerField(null=True)),
                ('date', models.CharField(max_length=125)),
                ('user', models.CharField(max_length=125)),
                ('features', models.ManyToManyField(to='main_app.feature')),
                ('features_en', models.ManyToManyField(null=True, to='main_app.feature')),
                ('features_ru', models.ManyToManyField(null=True, to='main_app.feature')),
                ('features_uz', models.ManyToManyField(null=True, to='main_app.feature')),
            ],
        ),
    ]
